const { neon } = require("@neondatabase/serverless");
const { getAdminLocketUids, getAdminLocketEmails } = require("./locketAdminVerifier");
const { getRequestContext } = require("./userActivityContext");

const ONLINE_WINDOW_SECONDS = 150;
let schemaPromise = null;

function getDatabaseUrl() {
  return [process.env.DATABASE_URL, process.env.NEON_DATABASE_URL]
    .find((value) => typeof value === "string" && value.trim())
    ?.trim() || null;
}

function getSql() {
  const databaseUrl = getDatabaseUrl();
  return databaseUrl ? neon(databaseUrl) : null;
}

function hasActivityDatabase() {
  return Boolean(getDatabaseUrl());
}

async function ensureUserActivitySchema() {
  const sql = getSql();
  if (!sql) {
    const error = new Error("User activity database is not configured");
    error.code = "DATABASE_NOT_CONFIGURED";
    throw error;
  }
  if (schemaPromise) return schemaPromise;

  schemaPromise = (async () => {
    await sql`CREATE TABLE IF NOT EXISTS web_users (
      uid TEXT PRIMARY KEY,
      internal_id UUID NOT NULL DEFAULT gen_random_uuid(),
      email TEXT,
      username TEXT,
      display_name TEXT,
      profile_picture TEXT,
      provider TEXT,
      disabled BOOLEAN NOT NULL DEFAULT FALSE,
      last_sign_in_at TIMESTAMPTZ,
      ip_address TEXT,
      browser TEXT,
      os TEXT,
      auth_provider TEXT NOT NULL DEFAULT 'locket-firebase',
      login_method TEXT NOT NULL DEFAULT 'unknown',
      account_status TEXT NOT NULL DEFAULT 'active',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_login_at TIMESTAMPTZ,
      last_seen_at TIMESTAMPTZ,
      last_logout_at TIMESTAMPTZ,
      current_web_source TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS internal_id UUID DEFAULT gen_random_uuid()`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS provider TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS disabled BOOLEAN DEFAULT FALSE`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_sign_in_at TIMESTAMPTZ`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS ip_address TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS browser TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS os TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS auth_provider TEXT DEFAULT 'locket-firebase'`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS login_method TEXT DEFAULT 'unknown'`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS account_status TEXT DEFAULT 'active'`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_logout_at TIMESTAMPTZ`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS current_web_source TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS gps_coordinates TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW()`;
    await sql`UPDATE web_users SET
      internal_id = COALESCE(internal_id, gen_random_uuid()),
      auth_provider = COALESCE(auth_provider, provider, 'locket-firebase'),
      login_method = COALESCE(login_method, 'unknown'),
      account_status = CASE WHEN COALESCE(disabled, FALSE) THEN 'locked' ELSE COALESCE(account_status, 'active') END,
      last_login_at = COALESCE(last_login_at, last_sign_in_at),
      last_seen_at = COALESCE(last_seen_at, last_sign_in_at),
      updated_at = COALESCE(updated_at, NOW())`;
    await sql`CREATE UNIQUE INDEX IF NOT EXISTS web_users_internal_id_idx ON web_users (internal_id)`;
    await sql`CREATE INDEX IF NOT EXISTS web_users_last_seen_idx ON web_users (last_seen_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS user_sessions (
      session_id UUID PRIMARY KEY,
      user_uid TEXT NOT NULL REFERENCES web_users(uid) ON DELETE CASCADE,
      web_source TEXT NOT NULL DEFAULT 'unknown',
      started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      ended_at TIMESTAMPTZ,
      status TEXT NOT NULL DEFAULT 'active'
    )`;
    await sql`CREATE INDEX IF NOT EXISTS user_sessions_user_idx ON user_sessions (user_uid, last_seen_at DESC)`;
    await sql`CREATE INDEX IF NOT EXISTS user_sessions_presence_idx ON user_sessions (status, last_seen_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS login_history (
      event_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      uid TEXT NOT NULL,
      session_id UUID,
      ip_address TEXT,
      country TEXT,
      region TEXT,
      city TEXT,
      browser TEXT,
      browser_version TEXT,
      os TEXT,
      device TEXT,
      login_method TEXT,
      web_source TEXT,
      web_version TEXT,
      build_id TEXT,
      commit_hash TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      ended_at TIMESTAMPTZ
    )`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS event_id BIGINT GENERATED BY DEFAULT AS IDENTITY`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS session_id UUID`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS region TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS browser_version TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS web_source TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS web_version TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS build_id TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS commit_hash TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS gps_coordinates TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ DEFAULT NOW()`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS ended_at TIMESTAMPTZ`;
    await sql`CREATE UNIQUE INDEX IF NOT EXISTS login_history_session_idx ON login_history (session_id) WHERE session_id IS NOT NULL`;
    await sql`CREATE INDEX IF NOT EXISTS login_history_user_idx ON login_history (uid, created_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS admin_audit_log (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      admin_uid TEXT NOT NULL,
      action TEXT NOT NULL,
      target_uid TEXT,
      details TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    await sql`ALTER TABLE admin_audit_log ADD COLUMN IF NOT EXISTS role TEXT`;
    await sql`ALTER TABLE admin_audit_log ADD COLUMN IF NOT EXISTS ip_address TEXT`;
    await sql`ALTER TABLE admin_audit_log ADD COLUMN IF NOT EXISTS web_source TEXT`;
    await sql`ALTER TABLE admin_audit_log ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'success'`;
    await sql`CREATE INDEX IF NOT EXISTS admin_audit_log_created_idx ON admin_audit_log (created_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS admin_roles (
      uid TEXT PRIMARY KEY,
      role TEXT NOT NULL DEFAULT 'user',
      assigned_by TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    await sql`ALTER TABLE admin_roles ADD COLUMN IF NOT EXISTS pin_hash TEXT`;

    await sql`CREATE TABLE IF NOT EXISTS admin_sessions (
      token_hash TEXT PRIMARY KEY,
      uid TEXT NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    await sql`CREATE INDEX IF NOT EXISTS admin_sessions_uid_idx ON admin_sessions (uid, expires_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS reported_content (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      content_id TEXT NOT NULL,
      content_type TEXT NOT NULL DEFAULT 'post',
      author_uid TEXT,
      reporter_uid TEXT,
      reason TEXT,
      status TEXT NOT NULL DEFAULT 'pending',
      action_taken TEXT,
      resolved_by TEXT,
      resolved_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;

    await sql`CREATE TABLE IF NOT EXISTS global_broadcasts (
      id INT PRIMARY KEY DEFAULT 1,
      message TEXT NOT NULL,
      level TEXT NOT NULL DEFAULT 'info',
      active BOOLEAN NOT NULL DEFAULT TRUE,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;

    await sql`CREATE TABLE IF NOT EXISTS ip_blacklist (
      ip_address TEXT PRIMARY KEY,
      reason TEXT,
      blocked_by TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;

    await sql`
      INSERT INTO web_users (uid, auth_provider, account_status, created_at, last_seen_at, current_web_source, updated_at)
      SELECT uid, 'locket-firebase', 'active', COALESCE(MIN(created_at), NOW()), COALESCE(MAX(created_at), NOW()), 'web-locket', NOW()
      FROM login_history
      GROUP BY uid
      ON CONFLICT (uid) DO NOTHING
    `;
    await loadBlacklistedIps().catch(() => {});
  })().catch((error) => {
    schemaPromise = null;
    throw error;
  });

  return schemaPromise;
}

function cleanOptional(value, maxLength = 320) {
  const clean = String(value || "").trim();
  return clean ? clean.slice(0, maxLength) : null;
}

function normalizeIdentity(decodedToken, verifiedProfile = null) {
  const uid = cleanOptional(decodedToken.uid || decodedToken.user_id, 160);
  if (!uid) throw new Error("Verified token has no user identifier");
  const email = cleanOptional(decodedToken.email || verifiedProfile?.email, 320)?.toLowerCase() || null;
  const profileName = [verifiedProfile?.firstName, verifiedProfile?.lastName]
    .map((value) => cleanOptional(value, 80))
    .filter(Boolean)
    .join(" ");
  return {
    uid,
    email,
    username: cleanOptional(verifiedProfile?.username || decodedToken.username, 120),
    displayName: cleanOptional(
      verifiedProfile?.displayName || profileName || decodedToken.name,
      160,
    ),
    profilePicture: cleanOptional(
      verifiedProfile?.profilePicture || decodedToken.picture,
      1000,
    ),
    authProvider: cleanOptional(decodedToken.firebase?.sign_in_provider, 80) || "locket-firebase",
  };
}

function shouldRecordLoginHistory(eventType) {
  return eventType === "login" || eventType === "resume";
}

async function getAccountStatus(uid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`SELECT account_status FROM web_users WHERE uid = ${uid} LIMIT 1`;
  return rows[0]?.account_status || "active";
}

async function upsertSession({ identity, sessionId, eventType, loginMethod, context, build, gps }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const isLogin = eventType === "login";
  const recordsHistory = shouldRecordLoginHistory(eventType);
  const method = cleanOptional(loginMethod, 40) || "unknown";
  const historyMethod = eventType === "resume" ? "session-resume" : method;
  const version = cleanOptional(build?.version, 40);
  const buildId = cleanOptional(build?.buildId, 120);
  const commitHash = cleanOptional(build?.commitHash, 80);
  const gpsCoord = cleanOptional(String(gps || ""), 120);

  await sql`
    INSERT INTO web_users (
      uid, email, username, display_name, profile_picture, auth_provider,
      login_method, account_status, last_login_at, last_seen_at,
      current_web_source, ip_address, browser, os, gps_coordinates, updated_at
    ) VALUES (
      ${identity.uid}, ${identity.email}, ${identity.username}, ${identity.displayName},
      ${identity.profilePicture}, ${identity.authProvider}, ${method}, 'active',
      ${isLogin ? new Date() : null}, NOW(), ${context.webSource}, ${context.ipAddress !== 'Không xác định' ? context.ipAddress : null}, ${context.browser !== 'Không xác định' ? context.browser : null}, ${context.os !== 'Không xác định' ? context.os : null}, ${gpsCoord}, NOW()
    )
    ON CONFLICT (uid) DO UPDATE SET
      email = COALESCE(EXCLUDED.email, web_users.email),
      username = COALESCE(EXCLUDED.username, web_users.username),
      display_name = COALESCE(EXCLUDED.display_name, web_users.display_name),
      profile_picture = COALESCE(EXCLUDED.profile_picture, web_users.profile_picture),
      auth_provider = EXCLUDED.auth_provider,
      login_method = CASE WHEN ${isLogin} THEN EXCLUDED.login_method ELSE web_users.login_method END,
      last_login_at = CASE WHEN ${isLogin} THEN NOW() ELSE web_users.last_login_at END,
      last_seen_at = NOW(),
      current_web_source = EXCLUDED.current_web_source,
      ip_address = COALESCE(EXCLUDED.ip_address, web_users.ip_address),
      browser = COALESCE(EXCLUDED.browser, web_users.browser),
      os = COALESCE(EXCLUDED.os, web_users.os),
      gps_coordinates = COALESCE(EXCLUDED.gps_coordinates, web_users.gps_coordinates),
      updated_at = NOW()
  `;

  const accountStatus = await getAccountStatus(identity.uid);
  if (accountStatus === "locked") {
    const error = new Error("Website account is locked");
    error.code = "ACCOUNT_LOCKED";
    throw error;
  }

  if (eventType === "resume" && sessionId) {
    const check = await sql`SELECT status FROM user_sessions WHERE session_id = ${sessionId} LIMIT 1`;
    if (check[0]?.status === 'revoked') {
      const error = new Error("Session has been revoked");
      error.code = "SESSION_REVOKED";
      throw error;
    }
  }

  await sql`
    INSERT INTO user_sessions (session_id, user_uid, web_source, started_at, last_seen_at, ended_at, status)
    VALUES (${sessionId}, ${identity.uid}, ${context.webSource}, NOW(), NOW(), NULL, 'active')
    ON CONFLICT (session_id) DO UPDATE SET
      last_seen_at = NOW(),
      ended_at = NULL,
      status = 'active',
      web_source = EXCLUDED.web_source
    WHERE user_sessions.user_uid = EXCLUDED.user_uid
  `;

  if (recordsHistory) {
    await sql`
      INSERT INTO login_history (
        uid, session_id, ip_address, country, region, city, browser,
        browser_version, os, device, login_method, web_source,
        web_version, build_id, commit_hash, gps_coordinates, created_at, last_seen_at
      ) VALUES (
        ${identity.uid}, ${sessionId}, ${context.ipAddress}, ${context.country},
        ${context.region}, ${context.city}, ${context.browser}, ${context.browserVersion},
        ${context.os}, ${context.device}, ${historyMethod}, ${context.webSource},
        ${version}, ${buildId}, ${commitHash}, ${gpsCoord}, NOW(), NOW()
      )
      ON CONFLICT (session_id) WHERE session_id IS NOT NULL DO UPDATE SET
        last_seen_at = NOW(),
        gps_coordinates = COALESCE(EXCLUDED.gps_coordinates, login_history.gps_coordinates)
      WHERE login_history.uid = EXCLUDED.uid
    `;
  }

  return { accountStatus };
}

async function heartbeatSession({ uid, sessionId, webSource, gps }) {
  await ensureUserActivitySchema();
  const accountStatus = await getAccountStatus(uid);
  if (accountStatus === "locked") {
    const error = new Error("Website account is locked");
    error.code = "ACCOUNT_LOCKED";
    throw error;
  }
  const sql = getSql();
  const gpsCoord = cleanOptional(String(gps || ""), 120);
  const check = await sql`SELECT status FROM user_sessions WHERE session_id = ${sessionId} AND user_uid = ${uid} LIMIT 1`;
  if (check[0]?.status === 'revoked') {
    const error = new Error("Session has been revoked");
    error.code = "SESSION_REVOKED";
    throw error;
  }
  await sql`
    INSERT INTO web_users (uid, auth_provider, account_status, last_seen_at, current_web_source, gps_coordinates, updated_at)
    VALUES (${uid}, 'locket-firebase', 'active', NOW(), ${webSource || 'web-locket'}, ${gpsCoord}, NOW())
    ON CONFLICT (uid) DO UPDATE SET
      last_seen_at = NOW(),
      current_web_source = COALESCE(EXCLUDED.current_web_source, web_users.current_web_source),
      gps_coordinates = COALESCE(EXCLUDED.gps_coordinates, web_users.gps_coordinates),
      updated_at = NOW()
  `;
  await sql`
    INSERT INTO user_sessions (session_id, user_uid, web_source, started_at, last_seen_at, status)
    VALUES (${sessionId}, ${uid}, ${webSource || 'web-locket'}, NOW(), NOW(), 'active')
    ON CONFLICT (session_id) DO UPDATE SET
      last_seen_at = NOW(), status = 'active', ended_at = NULL, web_source = EXCLUDED.web_source
    WHERE user_sessions.user_uid = ${uid}
  `;
  await sql`
    UPDATE login_history SET last_seen_at = NOW(), gps_coordinates = COALESCE(${gpsCoord}, gps_coordinates)
    WHERE session_id = ${sessionId} AND uid = ${uid}
  `;
}

async function endSession({ uid, sessionId }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  await sql`
    UPDATE user_sessions
    SET ended_at = NOW(), last_seen_at = NOW(), status = 'logged_out'
    WHERE session_id = ${sessionId} AND user_uid = ${uid}
  `;
  await sql`
    UPDATE login_history SET ended_at = NOW(), last_seen_at = NOW()
    WHERE session_id = ${sessionId} AND uid = ${uid}
  `;
  await sql`
    UPDATE web_users SET last_logout_at = NOW(), last_seen_at = NOW(), updated_at = NOW()
    WHERE uid = ${uid}
  `;
}

async function listWebUsers({ search = "", limit = 50, offset = 0 }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const normalizedSearch = cleanOptional(search, 160)?.toLowerCase() || "";
  const pattern = `%${normalizedSearch}%`;
  const rows = await sql`
    SELECT
      u.uid, u.internal_id, u.email, u.username, u.display_name,
      u.profile_picture, u.auth_provider, u.login_method, u.account_status,
      u.created_at, u.last_login_at, u.last_seen_at, u.last_logout_at,
      u.current_web_source, u.gps_coordinates,
      COALESCE(ro.role, 'user') AS role,
      COUNT(*) OVER()::int AS total_count,
      COALESCE(active.active_sessions, 0)::int AS active_sessions,
      COALESCE(latest.ip_address, u.ip_address) AS ip_address, latest.country, latest.region, latest.city,
      COALESCE(latest.browser, u.browser) AS browser, latest.browser_version, COALESCE(latest.os, u.os) AS os, latest.device,
      latest.login_method AS latest_login_method,
      COALESCE(latest.web_source, u.current_web_source) AS latest_web_source,
      latest.web_version, latest.build_id, latest.commit_hash,
      COALESCE(latest.gps_coordinates, u.gps_coordinates) AS latest_gps_coordinates,
      COALESCE(latest.created_at, u.last_seen_at, u.last_login_at) AS latest_login_event_at,
      latest.ended_at AS latest_session_ended_at
    FROM web_users u
    LEFT JOIN LATERAL (
      SELECT r.role FROM admin_roles r WHERE r.uid = u.uid LIMIT 1
    ) ro ON TRUE
    LEFT JOIN LATERAL (
      SELECT COUNT(*)::int AS active_sessions
      FROM user_sessions s
      WHERE s.user_uid = u.uid
        AND s.status = 'active'
        AND s.ended_at IS NULL
        AND s.last_seen_at >= NOW() - (${ONLINE_WINDOW_SECONDS} * INTERVAL '1 second')
    ) active ON TRUE
    LEFT JOIN LATERAL (
      SELECT h.* FROM login_history h
      WHERE h.uid = u.uid
      ORDER BY h.created_at DESC
      LIMIT 1
    ) latest ON TRUE
    WHERE ${normalizedSearch === ""}
      OR LOWER(COALESCE(u.email, '')) LIKE ${pattern}
      OR LOWER(COALESCE(u.username, '')) LIKE ${pattern}
      OR LOWER(COALESCE(u.display_name, '')) LIKE ${pattern}
      OR LOWER(u.uid) LIKE ${pattern}
    ORDER BY u.last_seen_at DESC NULLS LAST, u.created_at DESC
    LIMIT ${limit + 1} OFFSET ${offset}
  `;
  const hasMore = rows.length > limit;
  return {
    users: rows.slice(0, limit),
    total: rows[0]?.total_count || 0,
    nextOffset: hasMore ? offset + limit : null,
    onlineWindowSeconds: ONLINE_WINDOW_SECONDS,
  };
}

async function getLoginHistory(uid, limit = 100) {
  await ensureUserActivitySchema();
  const sql = getSql();
  return sql`
    SELECT event_id, session_id, ip_address, country, region, city,
      browser, browser_version, os, device, login_method, web_source,
      web_version, build_id, commit_hash, gps_coordinates, created_at, last_seen_at, ended_at
    FROM login_history
    WHERE uid = ${uid}
    ORDER BY created_at DESC
    LIMIT ${limit}
  `;
}

async function getWebUser(uid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    SELECT uid, email, display_name, account_status
    FROM web_users WHERE uid = ${uid} LIMIT 1
  `;
  return rows[0] || null;
}

async function clearLoginHistory(uid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`DELETE FROM login_history WHERE uid = ${uid} RETURNING event_id`;
  return rows.length;
}

async function setAccountStatus(uid, status) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    UPDATE web_users SET account_status = ${status}, updated_at = NOW()
    WHERE uid = ${uid} RETURNING uid
  `;
  return rows.length > 0;
}

async function writeAudit({ adminUid, role = null, action, targetUid = null, details = null, ipAddress = null, webSource = null, status = 'success' }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  await sql`
    INSERT INTO admin_audit_log (admin_uid, role, action, target_uid, details, ip_address, web_source, status)
    VALUES (${adminUid}, ${role}, ${action}, ${targetUid}, ${cleanOptional(details, 500)}, ${ipAddress}, ${webSource}, ${status})
  `;
}

async function getUserRole(uid, email) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const normalizedEmail = String(email || "").trim().toLowerCase();
  const isRootAdmin = getAdminLocketUids().has(uid) || (normalizedEmail && getAdminLocketEmails().has(normalizedEmail));
  if (isRootAdmin) {
    try {
      await sql`INSERT INTO admin_roles (uid, role, assigned_by) VALUES (${uid}, 'super_admin', 'bootstrap') ON CONFLICT (uid) DO UPDATE SET role = 'super_admin' WHERE admin_roles.uid = ${uid}`;
    } catch (err) {
      console.warn("Failed to bootstrap super_admin in admin_roles:", err.message);
    }
    return 'super_admin';
  }
  const rows = await sql`SELECT role FROM admin_roles WHERE uid = ${uid} LIMIT 1`;
  if (rows.length > 0 && rows[0]?.role) {
    return rows[0].role;
  }
  return 'user';
}

async function setUserRole(targetUid, newRole, assignedByUid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    INSERT INTO admin_roles (uid, role, assigned_by, updated_at)
    VALUES (${targetUid}, ${newRole}, ${assignedByUid}, NOW())
    ON CONFLICT (uid) DO UPDATE SET
      role = EXCLUDED.role,
      assigned_by = EXCLUDED.assigned_by,
      updated_at = NOW()
    RETURNING uid, role
  `;
  return rows[0] || null;
}

async function revokeUserSessions(uid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    UPDATE user_sessions
    SET ended_at = NOW(), status = 'revoked'
    WHERE user_uid = ${uid} AND (ended_at IS NULL OR status = 'active')
    RETURNING session_id
  `;
  await sql`
    UPDATE login_history SET ended_at = NOW()
    WHERE uid = ${uid} AND ended_at IS NULL
  `;
  return rows.length;
}

async function createAdminSession(uid, tokenHash, ttlMinutes = 30) {
  await ensureUserActivitySchema();
  const sql = getSql();
  await sql`
    INSERT INTO admin_sessions (token_hash, uid, expires_at, created_at)
    VALUES (${tokenHash}, ${uid}, NOW() + (${ttlMinutes} * INTERVAL '1 minute'), NOW())
    ON CONFLICT (token_hash) DO UPDATE SET
      expires_at = EXCLUDED.expires_at,
      uid = EXCLUDED.uid
  `;
}

async function verifyAdminSessionToken(uid, tokenHash, extendMinutes = 30) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    SELECT uid FROM admin_sessions
    WHERE token_hash = ${tokenHash} AND uid = ${uid} AND expires_at > NOW()
    LIMIT 1
  `;
  if (rows.length > 0) {
    await sql`
      UPDATE admin_sessions SET expires_at = NOW() + (${extendMinutes} * INTERVAL '1 minute')
      WHERE token_hash = ${tokenHash}
    `.catch(() => {});
    return true;
  }
  return false;
}

function hashPin(pin) {
  const crypto = require("node:crypto");
  return crypto.createHash("sha256").update(String(pin || "").trim() + "_huy_locket_pin_salt").digest("hex");
}

async function checkAdminPinSet(uid) {
  if (!uid) return false;
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`SELECT pin_hash FROM admin_roles WHERE uid = ${uid} LIMIT 1`;
  return Boolean(rows[0]?.pin_hash);
}

async function verifyAdminPin(uid, pin) {
  if (!uid || !pin) return false;
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`SELECT pin_hash FROM admin_roles WHERE uid = ${uid} LIMIT 1`;
  const storedHash = rows[0]?.pin_hash;
  if (!storedHash) return false;
  return hashPin(pin) === storedHash;
}

async function setAdminPin(uid, pin, role = "super_admin") {
  if (!uid || !pin) throw new Error("Missing uid or pin");
  await ensureUserActivitySchema();
  const sql = getSql();
  const hashed = hashPin(pin);
  await sql`
    INSERT INTO admin_roles (uid, role, pin_hash, assigned_by, updated_at)
    VALUES (${uid}, ${role}, ${hashed}, 'self', NOW())
    ON CONFLICT (uid) DO UPDATE SET pin_hash = EXCLUDED.pin_hash, updated_at = NOW()
  `;
  return true;
}

async function listAuditLogs({ action = "", adminUid = "", limit = 100, offset = 0 }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const patternAction = action ? `%${action}%` : null;
  const patternAdmin = adminUid ? `%${adminUid}%` : null;
  const rows = await sql`
    SELECT id, admin_uid, role, action, target_uid, details, ip_address, web_source, status, created_at,
           COUNT(*) OVER()::int AS total_count
    FROM admin_audit_log
    WHERE (${patternAction === null} OR action ILIKE ${patternAction})
      AND (${patternAdmin === null} OR admin_uid ILIKE ${patternAdmin})
    ORDER BY created_at DESC
    LIMIT ${limit} OFFSET ${offset}
  `;
  return {
    logs: rows,
    total: rows[0]?.total_count || 0
  };
}

async function listReportedContent({ status = "", limit = 50 }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const patternStatus = status ? status : null;
  const rows = await sql`
    SELECT * FROM reported_content
    WHERE (${patternStatus === null} OR status = ${patternStatus})
    ORDER BY created_at DESC
    LIMIT ${limit}
  `;
  return rows;
}

async function resolveReport({ id, actionTaken, resolvedBy }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    UPDATE reported_content
    SET status = 'resolved', action_taken = ${actionTaken}, resolved_by = ${resolvedBy}, resolved_at = NOW()
    WHERE id = ${id} RETURNING id
  `;
  return rows.length > 0;
}

async function recordServerUserActivity({ user, req, eventType = 'touch', loginMethod = 'unknown' }) {
  if (!hasActivityDatabase() || !user) return;
  try {
    await ensureUserActivitySchema();
    const sql = getSql();
    const uid = cleanOptional(user.uid || user.localId || user.user_id, 160);
    if (!uid) return;

    const email = cleanOptional(user.email || null, 320)?.toLowerCase() || null;
    const displayName = cleanOptional(user.displayName || user.name || null, 160);
    const picture = cleanOptional(user.picture || user.profilePicture || null, 1000);

    let webSource = "web-locket";
    if (req?.headers?.origin) webSource = String(req.headers.origin).slice(0, 120);
    else if (req?.headers?.referer) {
      try { webSource = new URL(req.headers.referer).origin.slice(0, 120); } catch {}
    }

    const ctx = req ? getRequestContext(req) : null;
    const ip = ctx?.ipAddress && ctx.ipAddress !== "Không xác định" ? ctx.ipAddress : null;
    const browser = ctx?.browser && ctx.browser !== "Không xác định" ? ctx.browser : null;
    const os = ctx?.os && ctx.os !== "Không xác định" ? ctx.os : null;
    const device = ctx?.device || null;

    const isLogin = eventType === "login";
    await sql`
      INSERT INTO web_users (
        uid, email, display_name, profile_picture, auth_provider,
        login_method, account_status, last_login_at, last_seen_at,
        current_web_source, ip_address, browser, os, updated_at
      ) VALUES (
        ${uid}, ${email}, ${displayName}, ${picture}, 'locket-firebase',
        ${cleanOptional(loginMethod, 40) || 'unknown'}, 'active', ${isLogin ? new Date() : null}, NOW(),
        ${webSource}, ${ip}, ${browser}, ${os}, NOW()
      )
      ON CONFLICT (uid) DO UPDATE SET
        email = COALESCE(EXCLUDED.email, web_users.email),
        display_name = COALESCE(EXCLUDED.display_name, web_users.display_name),
        profile_picture = COALESCE(EXCLUDED.profile_picture, web_users.profile_picture),
        login_method = CASE WHEN ${isLogin} THEN EXCLUDED.login_method ELSE web_users.login_method END,
        last_login_at = CASE WHEN ${isLogin} THEN NOW() ELSE web_users.last_login_at END,
        last_seen_at = NOW(),
        current_web_source = COALESCE(EXCLUDED.current_web_source, web_users.current_web_source),
        ip_address = COALESCE(EXCLUDED.ip_address, web_users.ip_address),
        browser = COALESCE(EXCLUDED.browser, web_users.browser),
        os = COALESCE(EXCLUDED.os, web_users.os),
        updated_at = NOW()
    `;

    if (ctx && (ip || browser || os)) {
      await sql`
        INSERT INTO login_history (
          uid, session_id, ip_address, country, region, city, browser,
          browser_version, os, device, login_method, web_source,
          web_version, created_at, last_seen_at
        )
        SELECT
          ${uid}, NULL, ${ctx.ipAddress || 'Không xác định'}, ${ctx.country || 'Không xác định'},
          ${ctx.region || 'Không xác định'}, ${ctx.city || 'Không xác định'}, ${ctx.browser || 'Không xác định'},
          ${ctx.browserVersion || '-'}, ${ctx.os || 'Không xác định'}, ${device || 'Không xác định'},
          ${cleanOptional(loginMethod, 40) || 'api-touch'}, ${webSource}, '-', NOW(), NOW()
        WHERE NOT EXISTS (
          SELECT 1 FROM login_history WHERE uid = ${uid} AND last_seen_at >= NOW() - INTERVAL '1 hour'
        )
      `;
    }
  } catch (error) {
    // Silent fail to avoid interrupting API responses
  }
}

async function purgeBotUsers(currentAdminUid = null) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const { getAdminLocketUids, getAdminLocketEmails } = require("./locketAdminVerifier");

  const users = await sql`
    SELECT
      u.uid, u.email, u.display_name, u.account_status,
      COALESCE(ro.role, 'user') AS role,
      COALESCE(latest.ip_address, u.ip_address) AS ip_address,
      COALESCE(latest.browser, u.browser) AS browser,
      COALESCE(latest.device, u.os, '') AS device
    FROM web_users u
    LEFT JOIN LATERAL (
      SELECT r.role FROM admin_roles r WHERE r.uid = u.uid LIMIT 1
    ) ro ON TRUE
    LEFT JOIN LATERAL (
      SELECT h.ip_address, h.browser, h.device FROM login_history h
      WHERE h.uid = u.uid
      ORDER BY h.created_at DESC
      LIMIT 1
    ) latest ON TRUE
    WHERE u.account_status != 'locked'
  `;

  const purgedList = [];
  for (const u of users) {
    if (u.uid === currentAdminUid || u.role === 'super_admin' || u.role === 'admin') continue;
    const normEmail = String(u.email || "").trim().toLowerCase();
    if (getAdminLocketUids().has(u.uid) || (normEmail && getAdminLocketEmails().has(normEmail))) continue;

    const ip = String(u.ip_address || "").trim();
    const browser = String(u.browser || "").trim().toLowerCase();
    const device = String(u.device || "").trim().toLowerCase();

    const isCloudIp = /^(54\.|3\.|18\.|13\.|52\.|50\.|23\.)/.test(ip);
    const isSuspiciousEmail = normEmail.startsWith("tiendai") || normEmail.includes("clone") || normEmail.includes("bot");

    // Chỉ trảm khi chắc chắn 100% là IP Máy chủ Cloud VPS hoặc Email dạng tool clone (không cào bằng những tài khoản thường cũ chưa ghi log trình duyệt)
    if (isCloudIp || isSuspiciousEmail) {
      await setAccountStatus(u.uid, "locked");
      await revokeUserSessions(u.uid);
      purgedList.push({ uid: u.uid, email: u.email, displayName: u.display_name, ip, reason: "Phát hiện Bot/Tool/VPS tự động" });
    }
  }

  return { purgedCount: purgedList.length, purgedUsers: purgedList };
}

// 1. Quyền Phát Sóng Thông Báo Toàn Cầu
async function setGlobalBroadcast(message, level = "info", active = true) {
  if (!sql) return { success: false };
  await sql`
    INSERT INTO global_broadcasts (id, message, level, active, updated_at)
    VALUES (1, ${message}, ${level}, ${active}, NOW())
    ON CONFLICT (id) DO UPDATE SET message = EXCLUDED.message, level = EXCLUDED.level, active = EXCLUDED.active, updated_at = NOW()
  `;
  return { success: true, message, level, active };
}

async function getGlobalBroadcast() {
  if (!sql) return { active: false, message: "" };
  const res = await sql`SELECT message, level, active, updated_at FROM global_broadcasts WHERE id = 1 AND active = TRUE LIMIT 1`;
  return res[0] ? { active: res[0].active, message: res[0].message, level: res[0].level, updatedAt: res[0].updated_at } : { active: false, message: "" };
}

// 2. Quyền Cấm Cửa Địa Chỉ IP Vĩnh Viễn
const blacklistedIpsMemory = new Set();
async function loadBlacklistedIps() {
  if (!sql) return;
  try {
    const res = await sql`SELECT ip_address FROM ip_blacklist`;
    blacklistedIpsMemory.clear();
    for (const row of res) {
      blacklistedIpsMemory.add(row.ip_address);
    }
  } catch {}
}

async function addIpBlacklist(ip_address, reason = "Banned by Admin", blocked_by = "SUPER_ADMIN") {
  if (!sql || !ip_address || ip_address === "Không xác định") return { success: false };
  await sql`
    INSERT INTO ip_blacklist (ip_address, reason, blocked_by, created_at)
    VALUES (${ip_address}, ${reason}, ${blocked_by}, NOW())
    ON CONFLICT (ip_address) DO UPDATE SET reason = EXCLUDED.reason, blocked_by = EXCLUDED.blocked_by, created_at = NOW()
  `;
  blacklistedIpsMemory.add(ip_address);
  return { success: true, ip_address };
}

async function removeIpBlacklist(ip_address) {
  if (!sql || !ip_address) return { success: false };
  await sql`DELETE FROM ip_blacklist WHERE ip_address = ${ip_address}`;
  blacklistedIpsMemory.delete(ip_address);
  return { success: true, ip_address };
}

async function listBlacklistedIps() {
  if (!sql) return [];
  return await sql`SELECT ip_address, reason, blocked_by, created_at FROM ip_blacklist ORDER BY created_at DESC LIMIT 1000`;
}

function isIpBlacklisted(ip) {
  return blacklistedIpsMemory.has(ip);
}

// 3. Quyền Xóa Khởi Tử Vĩnh Viễn Từng Tài Khoản
async function nukeUserPermanently(uid) {
  if (!sql || !uid) return { success: false };
  await sql`DELETE FROM login_history WHERE uid = ${uid} OR user_uid = ${uid}`;
  await sql`DELETE FROM user_sessions WHERE uid = ${uid}`;
  await sql`DELETE FROM web_users WHERE uid = ${uid}`;
  return { success: true };
}

// 4. Cảm Biến Giám Sát Tài Nguyên & Thống Kê Máy Chủ
function getServerHealthStats() {
  const memory = process.memoryUsage();
  const uptime = process.uptime();
  return {
    uptimeSeconds: Math.floor(uptime),
    memoryRssMb: Math.round(memory.rss / (1024 * 1024)),
    memoryHeapUsedMb: Math.round(memory.heapUsed / (1024 * 1024)),
    nodeVersion: process.version,
    platform: process.platform + " " + process.arch,
    status: "OPTIMAL (Huy Locket Shield Active)",
  };
}

// 5. Quyền kiểm tra trạng thái khôi phục Mật Khẩu (Password Recovery Status)
function getUserPasswordRecoveryStatus(email) {
  return {
    email: email || "Chưa gắn email",
    canResetViaFirebase: Boolean(email && email.includes("@")),
    secureDirectLinkSupported: true,
    policy: "Bảo vệ bởi Mã hóa chuẩn Locket Firebase. Không lưu bản rõ, nhưng hỗ trợ kích hoạt cổng đổi mật khẩu KHẨN CẤP khi người dùng quên.",
  };
}

module.exports = {
  ONLINE_WINDOW_SECONDS,
  addIpBlacklist,
  checkAdminPinSet,
  clearLoginHistory,
  createAdminSession,
  endSession,
  ensureUserActivitySchema,
  getAccountStatus,
  getGlobalBroadcast,
  getLoginHistory,
  getServerHealthStats,
  getUserPasswordRecoveryStatus,
  getUserRole,
  getWebUser,
  hasActivityDatabase,
  heartbeatSession,
  isIpBlacklisted,
  listAuditLogs,
  listBlacklistedIps,
  listReportedContent,
  listWebUsers,
  loadBlacklistedIps,
  normalizeIdentity,
  nukeUserPermanently,
  purgeBotUsers,
  recordServerUserActivity,
  removeIpBlacklist,
  resolveReport,
  revokeUserSessions,
  setAccountStatus,
  setAdminPin,
  setGlobalBroadcast,
  setUserRole,
  shouldRecordLoginHistory,
  upsertSession,
  verifyAdminPin,
  verifyAdminSessionToken,
  writeAudit,
};
