const { neon } = require("@neondatabase/serverless");

const ONLINE_WINDOW_SECONDS = 150;
let schemaPromise = null;

function getDatabaseUrl() {
  return [process.env.DATABASE_URL, process.env.NEON_DATABASE_URL]
    .find((value) => typeof value === "string" && value.trim())
    ?.trim() || null;
}

function getSql() {
  const databaseUrl = getDatabaseUrl();
  return databaseUrl ? neon(databaseUrl) : null;
}

function hasActivityDatabase() {
  return Boolean(getDatabaseUrl());
}

async function ensureUserActivitySchema() {
  const sql = getSql();
  if (!sql) {
    const error = new Error("User activity database is not configured");
    error.code = "DATABASE_NOT_CONFIGURED";
    throw error;
  }
  if (schemaPromise) return schemaPromise;

  schemaPromise = (async () => {
    await sql`CREATE TABLE IF NOT EXISTS web_users (
      uid TEXT PRIMARY KEY,
      internal_id UUID NOT NULL DEFAULT gen_random_uuid(),
      email TEXT,
      username TEXT,
      display_name TEXT,
      profile_picture TEXT,
      provider TEXT,
      disabled BOOLEAN NOT NULL DEFAULT FALSE,
      last_sign_in_at TIMESTAMPTZ,
      ip_address TEXT,
      browser TEXT,
      os TEXT,
      auth_provider TEXT NOT NULL DEFAULT 'locket-firebase',
      login_method TEXT NOT NULL DEFAULT 'unknown',
      account_status TEXT NOT NULL DEFAULT 'active',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_login_at TIMESTAMPTZ,
      last_seen_at TIMESTAMPTZ,
      last_logout_at TIMESTAMPTZ,
      current_web_source TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS internal_id UUID DEFAULT gen_random_uuid()`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS provider TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS disabled BOOLEAN DEFAULT FALSE`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_sign_in_at TIMESTAMPTZ`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS ip_address TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS browser TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS os TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS auth_provider TEXT DEFAULT 'locket-firebase'`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS login_method TEXT DEFAULT 'unknown'`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS account_status TEXT DEFAULT 'active'`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS last_logout_at TIMESTAMPTZ`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS current_web_source TEXT`;
    await sql`ALTER TABLE web_users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW()`;
    await sql`UPDATE web_users SET
      internal_id = COALESCE(internal_id, gen_random_uuid()),
      auth_provider = COALESCE(auth_provider, provider, 'locket-firebase'),
      login_method = COALESCE(login_method, 'unknown'),
      account_status = CASE WHEN COALESCE(disabled, FALSE) THEN 'locked' ELSE COALESCE(account_status, 'active') END,
      last_login_at = COALESCE(last_login_at, last_sign_in_at),
      last_seen_at = COALESCE(last_seen_at, last_sign_in_at),
      updated_at = COALESCE(updated_at, NOW())`;
    await sql`CREATE UNIQUE INDEX IF NOT EXISTS web_users_internal_id_idx ON web_users (internal_id)`;
    await sql`CREATE INDEX IF NOT EXISTS web_users_last_seen_idx ON web_users (last_seen_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS user_sessions (
      session_id UUID PRIMARY KEY,
      user_uid TEXT NOT NULL REFERENCES web_users(uid) ON DELETE CASCADE,
      web_source TEXT NOT NULL DEFAULT 'unknown',
      started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      ended_at TIMESTAMPTZ,
      status TEXT NOT NULL DEFAULT 'active'
    )`;
    await sql`CREATE INDEX IF NOT EXISTS user_sessions_user_idx ON user_sessions (user_uid, last_seen_at DESC)`;
    await sql`CREATE INDEX IF NOT EXISTS user_sessions_presence_idx ON user_sessions (status, last_seen_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS login_history (
      event_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      uid TEXT NOT NULL,
      session_id UUID,
      ip_address TEXT,
      country TEXT,
      region TEXT,
      city TEXT,
      browser TEXT,
      browser_version TEXT,
      os TEXT,
      device TEXT,
      login_method TEXT,
      web_source TEXT,
      web_version TEXT,
      build_id TEXT,
      commit_hash TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      ended_at TIMESTAMPTZ
    )`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS event_id BIGINT GENERATED BY DEFAULT AS IDENTITY`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS session_id UUID`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS region TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS browser_version TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS web_source TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS web_version TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS build_id TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS commit_hash TEXT`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ DEFAULT NOW()`;
    await sql`ALTER TABLE login_history ADD COLUMN IF NOT EXISTS ended_at TIMESTAMPTZ`;
    await sql`CREATE UNIQUE INDEX IF NOT EXISTS login_history_session_idx ON login_history (session_id) WHERE session_id IS NOT NULL`;
    await sql`CREATE INDEX IF NOT EXISTS login_history_user_idx ON login_history (uid, created_at DESC)`;

    await sql`CREATE TABLE IF NOT EXISTS admin_audit_log (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      admin_uid TEXT NOT NULL,
      action TEXT NOT NULL,
      target_uid TEXT,
      details TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;
    await sql`CREATE INDEX IF NOT EXISTS admin_audit_log_created_idx ON admin_audit_log (created_at DESC)`;
  })().catch((error) => {
    schemaPromise = null;
    throw error;
  });

  return schemaPromise;
}

function cleanOptional(value, maxLength = 320) {
  const clean = String(value || "").trim();
  return clean ? clean.slice(0, maxLength) : null;
}

function normalizeIdentity(decodedToken, verifiedProfile = null) {
  const uid = cleanOptional(decodedToken.uid || decodedToken.user_id, 160);
  if (!uid) throw new Error("Verified token has no user identifier");
  const email = cleanOptional(decodedToken.email || verifiedProfile?.email, 320)?.toLowerCase() || null;
  const profileName = [verifiedProfile?.firstName, verifiedProfile?.lastName]
    .map((value) => cleanOptional(value, 80))
    .filter(Boolean)
    .join(" ");
  return {
    uid,
    email,
    username: cleanOptional(verifiedProfile?.username || decodedToken.username, 120),
    displayName: cleanOptional(
      verifiedProfile?.displayName || profileName || decodedToken.name,
      160,
    ),
    profilePicture: cleanOptional(
      verifiedProfile?.profilePicture || decodedToken.picture,
      1000,
    ),
    authProvider: cleanOptional(decodedToken.firebase?.sign_in_provider, 80) || "locket-firebase",
  };
}

function shouldRecordLoginHistory(eventType) {
  return eventType === "login" || eventType === "resume";
}

async function getAccountStatus(uid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`SELECT account_status FROM web_users WHERE uid = ${uid} LIMIT 1`;
  return rows[0]?.account_status || "active";
}

async function upsertSession({ identity, sessionId, eventType, loginMethod, context, build }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const isLogin = eventType === "login";
  const recordsHistory = shouldRecordLoginHistory(eventType);
  const method = cleanOptional(loginMethod, 40) || "unknown";
  const historyMethod = eventType === "resume" ? "session-resume" : method;
  const version = cleanOptional(build?.version, 40);
  const buildId = cleanOptional(build?.buildId, 120);
  const commitHash = cleanOptional(build?.commitHash, 80);

  await sql`
    INSERT INTO web_users (
      uid, email, username, display_name, profile_picture, auth_provider,
      login_method, account_status, last_login_at, last_seen_at,
      current_web_source, updated_at
    ) VALUES (
      ${identity.uid}, ${identity.email}, ${identity.username}, ${identity.displayName},
      ${identity.profilePicture}, ${identity.authProvider}, ${method}, 'active',
      ${isLogin ? new Date() : null}, NOW(), ${context.webSource}, NOW()
    )
    ON CONFLICT (uid) DO UPDATE SET
      email = COALESCE(EXCLUDED.email, web_users.email),
      username = COALESCE(EXCLUDED.username, web_users.username),
      display_name = COALESCE(EXCLUDED.display_name, web_users.display_name),
      profile_picture = COALESCE(EXCLUDED.profile_picture, web_users.profile_picture),
      auth_provider = EXCLUDED.auth_provider,
      login_method = CASE WHEN ${isLogin} THEN EXCLUDED.login_method ELSE web_users.login_method END,
      last_login_at = CASE WHEN ${isLogin} THEN NOW() ELSE web_users.last_login_at END,
      last_seen_at = NOW(),
      current_web_source = EXCLUDED.current_web_source,
      updated_at = NOW()
  `;

  const accountStatus = await getAccountStatus(identity.uid);
  if (accountStatus === "locked") {
    const error = new Error("Website account is locked");
    error.code = "ACCOUNT_LOCKED";
    throw error;
  }

  await sql`
    INSERT INTO user_sessions (session_id, user_uid, web_source, started_at, last_seen_at, ended_at, status)
    VALUES (${sessionId}, ${identity.uid}, ${context.webSource}, NOW(), NOW(), NULL, 'active')
    ON CONFLICT (session_id) DO UPDATE SET
      last_seen_at = NOW(),
      ended_at = NULL,
      status = 'active',
      web_source = EXCLUDED.web_source
    WHERE user_sessions.user_uid = EXCLUDED.user_uid
  `;

  if (recordsHistory) {
    await sql`
      INSERT INTO login_history (
        uid, session_id, ip_address, country, region, city, browser,
        browser_version, os, device, login_method, web_source,
        web_version, build_id, commit_hash, created_at, last_seen_at
      ) VALUES (
        ${identity.uid}, ${sessionId}, ${context.ipAddress}, ${context.country},
        ${context.region}, ${context.city}, ${context.browser}, ${context.browserVersion},
        ${context.os}, ${context.device}, ${historyMethod}, ${context.webSource},
        ${version}, ${buildId}, ${commitHash}, NOW(), NOW()
      )
      ON CONFLICT (session_id) WHERE session_id IS NOT NULL DO UPDATE SET
        last_seen_at = NOW()
      WHERE login_history.uid = EXCLUDED.uid
    `;
  }

  return { accountStatus };
}

async function heartbeatSession({ uid, sessionId, webSource }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  await sql`
    UPDATE user_sessions
    SET last_seen_at = NOW(), status = 'active', ended_at = NULL, web_source = ${webSource}
    WHERE session_id = ${sessionId} AND user_uid = ${uid}
  `;
  await sql`
    UPDATE web_users
    SET last_seen_at = NOW(), current_web_source = ${webSource}, updated_at = NOW()
    WHERE uid = ${uid}
  `;
  await sql`
    UPDATE login_history SET last_seen_at = NOW()
    WHERE session_id = ${sessionId} AND uid = ${uid}
  `;
}

async function endSession({ uid, sessionId }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  await sql`
    UPDATE user_sessions
    SET ended_at = NOW(), last_seen_at = NOW(), status = 'logged_out'
    WHERE session_id = ${sessionId} AND user_uid = ${uid}
  `;
  await sql`
    UPDATE login_history SET ended_at = NOW(), last_seen_at = NOW()
    WHERE session_id = ${sessionId} AND uid = ${uid}
  `;
  await sql`
    UPDATE web_users SET last_logout_at = NOW(), last_seen_at = NOW(), updated_at = NOW()
    WHERE uid = ${uid}
  `;
}

async function listWebUsers({ search = "", limit = 50, offset = 0 }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const normalizedSearch = cleanOptional(search, 160)?.toLowerCase() || "";
  const pattern = `%${normalizedSearch}%`;
  const rows = await sql`
    SELECT
      u.uid, u.internal_id, u.email, u.username, u.display_name,
      u.profile_picture, u.auth_provider, u.login_method, u.account_status,
      u.created_at, u.last_login_at, u.last_seen_at, u.last_logout_at,
      u.current_web_source,
      COUNT(*) OVER()::int AS total_count,
      COALESCE(active.active_sessions, 0)::int AS active_sessions,
      latest.ip_address, latest.country, latest.region, latest.city,
      latest.browser, latest.browser_version, latest.os, latest.device,
      latest.login_method AS latest_login_method,
      latest.web_source AS latest_web_source,
      latest.web_version, latest.build_id, latest.commit_hash,
      latest.created_at AS latest_login_event_at,
      latest.ended_at AS latest_session_ended_at
    FROM web_users u
    LEFT JOIN LATERAL (
      SELECT COUNT(*)::int AS active_sessions
      FROM user_sessions s
      WHERE s.user_uid = u.uid
        AND s.status = 'active'
        AND s.ended_at IS NULL
        AND s.last_seen_at >= NOW() - (${ONLINE_WINDOW_SECONDS} * INTERVAL '1 second')
    ) active ON TRUE
    LEFT JOIN LATERAL (
      SELECT h.* FROM login_history h
      WHERE h.uid = u.uid
      ORDER BY h.created_at DESC
      LIMIT 1
    ) latest ON TRUE
    WHERE ${normalizedSearch === ""}
      OR LOWER(COALESCE(u.email, '')) LIKE ${pattern}
      OR LOWER(COALESCE(u.username, '')) LIKE ${pattern}
      OR LOWER(COALESCE(u.display_name, '')) LIKE ${pattern}
      OR LOWER(u.uid) LIKE ${pattern}
    ORDER BY u.last_seen_at DESC NULLS LAST, u.created_at DESC
    LIMIT ${limit + 1} OFFSET ${offset}
  `;
  const hasMore = rows.length > limit;
  return {
    users: rows.slice(0, limit),
    total: rows[0]?.total_count || 0,
    nextOffset: hasMore ? offset + limit : null,
    onlineWindowSeconds: ONLINE_WINDOW_SECONDS,
  };
}

async function getLoginHistory(uid, limit = 100) {
  await ensureUserActivitySchema();
  const sql = getSql();
  return sql`
    SELECT event_id, session_id, ip_address, country, region, city,
      browser, browser_version, os, device, login_method, web_source,
      web_version, build_id, commit_hash, created_at, last_seen_at, ended_at
    FROM login_history
    WHERE uid = ${uid}
    ORDER BY created_at DESC
    LIMIT ${limit}
  `;
}

async function getWebUser(uid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    SELECT uid, email, display_name, account_status
    FROM web_users WHERE uid = ${uid} LIMIT 1
  `;
  return rows[0] || null;
}

async function clearLoginHistory(uid) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`DELETE FROM login_history WHERE uid = ${uid} RETURNING event_id`;
  return rows.length;
}

async function setAccountStatus(uid, status) {
  await ensureUserActivitySchema();
  const sql = getSql();
  const rows = await sql`
    UPDATE web_users SET account_status = ${status}, updated_at = NOW()
    WHERE uid = ${uid} RETURNING uid
  `;
  return rows.length > 0;
}

async function writeAudit({ adminUid, action, targetUid = null, details = null }) {
  await ensureUserActivitySchema();
  const sql = getSql();
  await sql`
    INSERT INTO admin_audit_log (admin_uid, action, target_uid, details)
    VALUES (${adminUid}, ${action}, ${targetUid}, ${cleanOptional(details, 500)})
  `;
}

module.exports = {
  ONLINE_WINDOW_SECONDS,
  clearLoginHistory,
  endSession,
  ensureUserActivitySchema,
  getAccountStatus,
  getLoginHistory,
  getWebUser,
  hasActivityDatabase,
  heartbeatSession,
  listWebUsers,
  normalizeIdentity,
  setAccountStatus,
  shouldRecordLoginHistory,
  upsertSession,
  writeAudit,
};
